### PR TITLE
Missing migration

### PR DESCRIPTION
**Pull request by lucbelliveau**

### CODE REVIEW

**Comment by bartjkdp** [comment]
@lucbelliveau @AadSchippers not sure where this migration comes from?

**Comment by lucbelliveau** [comment]
On master when you run migrate, it informs me that there is a missing migration...

**Comment by bartjkdp** [comment]
I have problems reproducing the behavior. Maybe you did some experimenting with your local database? My steps:

    git clone git@github.com:Pleio/pleio_account.git

Create a config.py by example of config.example.py

    mkvirtualenv pleio_account
    pip3 install -r requirements.txt
    python3 manage.py migrate
    python3 manage.py runserver

**Comment by lucbelliveau** [comment]
I'll double check.  I was working off the gctools fork master...

**Comment by lucbelliveau** [comment]
@bartjkdp Confirmed with your branch.  Just run migrate again in your steps above, the output looks lke this:

```
Operations to perform:
  Apply all migrations: admin, auth, axes, contenttypes, core, oauth2_provider, otp_static, otp_totp, two_factor, user_sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

I took a look at the migration files and the related_name property on the user field in the PreviousLogins model is indeed missing.

The change comes from this commit: 
 https://github.com/Pleio/pleio_account/commit/f86e809221a9b113f4f9eb0d523ea1c8f7499ad2

**Comment by AadSchippers** [comment]
@lucbelliveau You're absolutely correct, I'll merge the request right away. Sorry for the inconvenience.

**Pull request merged**
