### PR TITLE
Add OpenID Connect authorization

### PR DESCRIPTION
**Pull request by markwooff**

### CODE REVIEW

**Comment by bartjkdp** [comment]
I am really sorry @markwooff it is taking so long. It is crazy busy over here. I have no problems when some other person (e.g. someone else from your team) is reviewing this pull request. Will take a look early next week.

**Comment by markwooff** [comment]
No need to apologize @bartjkdp ! We know how busy it can get, especially after the holidays. We have this PR merged in our fork of `pleio_account` and haven't run into any issues except for the redirect issue (https://github.com/Pleio/pleio_account/issues/33).

**Comment by markwooff** [comment]
No problem @bartjkdp, just fixed the small merge conflicts. Merging in now!

**Comment by bartjkdp** [comment]
Thanks a lot! Going to experiment with connecting some applications really soon!

**Pull request merged**
